# Generated by Django 5.0.1 on 2024-01-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.pngitem.com%2Fpimgs%2Fm%2F35-350426_profile-icon-png-default-profile-picture-png-transparent.png&tbnid=X8BzrMqkPQLayM&vet=12ahUKEwiGg4_4lcWDAxUru2MGHZXVCdoQMyhAegUIARDtAQ..i&imgrefurl=https%3A%2F%2Fwww.megatruenet.com%2F%3Fk%3Ddefault-profile-icons-free-svg-png-default-profile-images-3-dd-5ewZnpt5&docid=DDKPasujT8UGPM&w=860&h=609&itg=1&q=default%20image%20png&ved=2ahUKEwiGg4_4lcWDAxUru2MGHZXVCdoQMyhAegUIARDtAQ', upload_to='profile/'),
        ),
    ]
